---
- src: geerlingguy.homebrew
- src: fubarhouse.macdock
- src: https://github.com/wufpack00/ansible-role-osx-defaults
  version: master
  name: wufpack00.ansible-role-osx-defaults
- src: geerlingguy.dotfiles