---
- name: Get the path to ZSH
  become: false
  local_action: command which zsh
  register: zsh_path

- name: "Ensure homebrew zsh is in allowed shells"
  lineinfile:
    path: /etc/shells
    line: "{{ zsh_path.stdout }}"
  become: true

- name: Install Oh My ZSH
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ omzsh_install_dir }}"

- name: Set ZSH as the default shell
  shell: chsh -s $(which zsh) {{ lookup('env', 'USER') }}
  become: true

- name: Remove .zshrc file created by install script
  file:
    path: "{{ dotfiles_home }}/.zshrc"
    state: absent

- name: Create symlink to custom .zshrc
  file:
    src: "{{ dotfiles_repo_local_destination }}/.zshrc"
    dest: "{{ dotfiles_home }}/.zshrc"
    state: link
    mode: 0644
  become: false

- name: Cloning zsh-autosuggestions plugin
  git:
    repo=https://github.com/zsh-users/zsh-autosuggestions
    dest="{{ omzsh_plugin_dir }}/zsh-autosuggestions"

- name: Cloning zsh-syntax-highlighting plugin
  git:
    repo=https://github.com/zsh-users/zsh-syntax-highlighting
    dest="{{ omzsh_plugin_dir }}/zsh-syntax-highlighting"