---
- name: Create a default VSCode configuration
  ansible.builtin.copy:
    src: vscode-settings.json
    dest: "{{ user_home_dir }}/Library/Application Support/Code/User/settings.json"
    owner: "{{ lookup('env', 'USER') }}"
    force: yes

# Add something which ensures path is set here
- name: Install VSCode extensions
  shell: code --install-extension {{ item }}
  with_items: "{{ vscode_extensions }}"

