configure_dotfiles: true

# The git repository and branch/tag/commit hash to use for retrieving dotfiles. Dotfiles should generally be laid out within the root directory of the repository.
dotfiles_repo: "https://github.com/wufpack00/dotfiles.git"
dotfiles_repo_version: minimal

#Add the hostkey for the repo url if not already added. If ssh_opts contains "-o StrictHostKeyChecking=no", this parameter is ignored.
dotfiles_repo_accept_hostkey: false

# The local path where the dotfiles_repo will be cloned.
dotfiles_repo_local_destination: "~/.dotfiles"

# The home directory where dotfiles will be linked.
dotfiles_home: "~"

#Which files from the dotfiles repository should be linked to the dotfiles_home
dotfiles_files:
  - .zshrc
  - .zshrc.personal.before
  - .zshrc.personal.after
  - .gitconfig
